// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxXw1OBd-iU9ro34E_DXHbDlSQCbDUM2g',
    appId: '1:329699147077:android:268ce6fa811c37a09e522c',
    messagingSenderId: '329699147077',
    projectId: 'ai-chatbot-app-716bd',
    storageBucket: 'ai-chatbot-app-716bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS1TOH-2BptqZZJfFfKxWTOwKLg7SWZIk',
    appId: '1:329699147077:ios:661d5420415507aa9e522c',
    messagingSenderId: '329699147077',
    projectId: 'ai-chatbot-app-716bd',
    storageBucket: 'ai-chatbot-app-716bd.firebasestorage.app',
    iosBundleId: 'com.example.edubot',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_iOoM-kWLiRKe9Q470z8GdbOm-Kv8tUw',
    appId: '1:329699147077:web:47ddecb54c36865d9e522c',
    messagingSenderId: '329699147077',
    projectId: 'ai-chatbot-app-716bd',
    authDomain: 'ai-chatbot-app-716bd.firebaseapp.com',
    storageBucket: 'ai-chatbot-app-716bd.firebasestorage.app',
  );

}